version: '3'
services:

  postgres:
    container_name: "postgres"
    image: postgres:9.3
    ports:
      - "5432:5432"  
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - cakenginx

  nginx:
    container_name: "nginx"
    build:
      context: "./"
      dockerfile: "Dockerfile_nginx"
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - cakenginx

  php:
    container_name: "php_fpm"
    build:
      context: "./"
      dockerfile: "Dockerfile_php"
    ports:
      - 9000:9000      
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST
      - DB_USER
      - DB_NAME
      - DB_PASSWORD
    depends_on:
      - "postgres"
    networks:
      - cakenginx

networks:
  cakenginx:
    driver: bridge