version: '3'
services:

  postgres:
    container_name: "postgres"
    image: postgres:9.3
    ports:
      - "5432:5432"  
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  php:
    container_name: "php"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    ports:
      - "8080:80"
    depends_on:
      - "postgres"